var dir_4d5751fd905cc7875fdd9c5cf7917ef7 =
[
    [ "charged_mom.h", "charged__mom_8h_source.html", null ],
    [ "chi2_dist.h", "chi2__dist_8h_source.html", null ],
    [ "clear_variables.h", "clear__variables_8h_source.html", null ],
    [ "closest_approach.h", "closest__approach_8h_source.html", null ],
    [ "constraints_omega.h", "constraints__omega_8h_source.html", null ],
    [ "constraints_tri.h", "constraints__tri_8h_source.html", null ],
    [ "ConstraintsOmega.h", "ConstraintsOmega_8h_source.html", null ],
    [ "cylinder_intersection.h", "cylinder__intersection_8h_source.html", null ],
    [ "DoubleRatio.h", "DoubleRatio_8h_source.html", null ],
    [ "EfficiencyAnalysis.h", "EfficiencyAnalysis_8h_source.html", null ],
    [ "ErrorLogs.h", "ErrorLogs_8h_source.html", null ],
    [ "fraction_fitter.h", "fraction__fitter_8h_source.html", null ],
    [ "interf_function.h", "interf__function_8h_source.html", null ],
    [ "interference.h", "interference_8h_source.html", null ],
    [ "jsonReader.h", "jsonReader_8h_source.html", null ],
    [ "KinFit.h", "KinFit_8h_source.html", null ],
    [ "KinFitter.h", "KinFitter_8h_source.html", null ],
    [ "kloe_class.h", "kloe__class_8h_source.html", null ],
    [ "Logs.h", "Logs_8h_source.html", null ],
    [ "lorentz_transf.h", "lorentz__transf_8h_source.html", null ],
    [ "MainMenu.h", "MainMenu_8h_source.html", null ],
    [ "neu_triangle.h", "neu__triangle_8h_source.html", null ],
    [ "neutral_mom.h", "neutral__mom_8h_source.html", null ],
    [ "pi0_photon_pair.h", "pi0__photon__pair_8h_source.html", null ],
    [ "plane_intersection.h", "plane__intersection_8h_source.html", null ],
    [ "RealTimeIntegration.h", "RealTimeIntegration_8h_source.html", null ],
    [ "reconstructor.h", "reconstructor_8h_source.html", null ],
    [ "triple_gaus.h", "triple__gaus_8h_source.html", null ],
    [ "uncertainties.h", "uncertainties_8h_source.html", null ]
];